replicaCount: 1
image:
  repository: ghcr.io/benflux-company/fluxchat-docs
  tag: 2e560ca85245d5c933622633352b6f0868144eb0
  pullPolicy: Always
service:
  port: 80
  targetPort: 3000
healthCheck:
  path: /
autoscaling:
  enabled: false
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 384Mi
env:
  NODE_ENV: production
  APP_ENV: dev
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
resourceQuota:
  requestsCpu: 200m
  requestsMemory: 256Mi
  limitsCpu: 500m
  limitsMemory: 768Mi
limitRange:
  defaultRequestCpu: 50m
  defaultRequestMemory: 128Mi
  defaultLimitCpu: 250m
  defaultLimitMemory: 384Mi
ingress:
  enabled: true
  host: dev-docs.fluxchat-corp.com
network:
  allowedIngressNamespaces: []
